[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "lanterne"
version = "0.1.0"
description = "Lib for mutliplayer in pygame - build for EPITA 2031 "
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = ["pytest"]